apiVersion: v1
kind: Service
metadata:
  labels:
    app: dataforwarding
  name: dataforwardingservice
spec:
  clusterIP: None
  ports:
  - name: metrics-port
    port: 9606
  - name: zmq-port
    port: 5501
  selector:
    app: dataforwarding
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: dataforwarding
    project: techflex
  name: dataforwardingservice
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: dataforwarding
  serviceName: dataforwardingservice
  template:
    metadata:
      labels:
        app: dataforwarding
    spec:
      containers:
      - env:
        - name: PUBSUB_DISCOVERY_ETCD_SERVER_IP
          value: etcd
        - name: PSA_IP
          value: dataforwardingservice
        - name: OTEL_COLLECTOR_URL
          value: otelcollector:4318/v1/traces
        - name: PSA_ZMQ_DEFAULT_BASE_PORT
          value: '5501'
        - name: PSA_ZMQ_DEFAULT_MAX_PORT
          value: '5501'
        image: ghcr.io/bruno-uva/dataforwarding:latest
        imagePullPolicy: Always
        name: dataforwardingservice-app
        resources:
          limits:
            memory: 1024M
            cpu: "1"
          requests:
            memory: 1024M
            cpu: "1"
        ports:
        - containerPort: 9606
          name: metrics-port
        - containerPort: 5501
          name: zmq-port
        stdin: true
        tty: true
      imagePullSecrets:
      - name: ghcr-pull-secret
