apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datatestservice-monitor
  labels:
    app: datatest
spec:
  endpoints:
  - interval: 1s
    port: metrics-port
  selector:
    matchLabels:
      app: datatest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: datatest
  name: datatestservice
spec:
  clusterIP: None
  ports:
  - name: metrics-port
    port: 9607
  - name: zmq-port
    port: 5501
  selector:
    app: datatest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: datatest
    project: techflex
  name: datatestservice
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: datatest
  serviceName: datatestservice
  template:
    metadata:
      labels:
        app: datatest
    spec:
      containers:
      - env:
        - name: PUBSUB_DISCOVERY_ETCD_SERVER_IP
          value: etcd
        - name: PSA_IP
          value: datatestservice
        - name: OTEL_COLLECTOR_URL
          value: otelcollector:4318/v1/traces
        - name: PSA_ZMQ_DEFAULT_BASE_PORT
          value: '5501'
        - name: PSA_ZMQ_DEFAULT_MAX_PORT
          value: '5501'
        image: ghcr.io/bruno-uva/datatest:latest
        imagePullPolicy: Always
        name: datatestservice-app
        ports:
        - containerPort: 9607
          name: metrics-port
        - containerPort: 5501
          name: zmq-port
        stdin: true
        tty: true
      imagePullSecrets:
      - name: ghcr-pull-secret