apiVersion: v1
kind: Service
metadata:
  name: deliverycontrolservice
#  namespace: techflex
  labels:
    app: deliverycontrol
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9600'
spec:
  ports:
    - name: app-metrics-port
      port: 9600
    - name: app-zmq-port
      port: 5501
  selector:
    app: deliverycontrol
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: deliverycontrol-ws
#  namespace: techflex
  labels:
    app: deliverycontrol
    project: techflex
spec:
  ports:
    - name: app-websocket-port
      port: 8080
      nodePort: 31001
  selector:
    app: deliverycontrol
  type: NodePort  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deliverycontrolservice
#  namespace: techflex
  labels:
    app: deliverycontrol
spec:
  serviceName: deliverycontrolservice
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: deliverycontrol
  template:
    metadata:
      labels:
        app: deliverycontrol
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret

      containers:
        - name: deliverycontrolservice-app
          image: ghcr.io/bruno-uva/deliverycontrol:latest
          imagePullPolicy: "Always"
          resources:
            stdin: true
            tty: true
          ports:
            ## Omitted
            - containerPort: 9600
            - containerPort: 5501
          env:
            - name: PUBSUB_DISCOVERY_ETCD_SERVER_IP
              value: etcd
            - name: PSA_IP 
              value: deliverycontrolservice
            - name: OTEL_COLLECTOR_URL
              value: otelcollector:4318/v1/traces
            - name: PSA_ZMQ_DEFAULT_BASE_PORT
              value: "5501"
            - name: PSA_ZMQ_DEFAULT_MAX_PORT
              value: "5501"
